version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - EMAIL_USER=globeviksoftware@gmail.com
      - EMAIL_PASS=euhibaxhnxpbtgii
    restart: always
